spring:
  application:
    name:activity-service
  data:
    mongodb:
      uri: mongodb+srv://singhswekccha:Mongo@cluster0.nnvhefo.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: fitnessactivity


server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/