server:
  port: 8082

spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb+srv://singhswekccha:Mongo@cluster0.nnvhefo.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: fitnessrecommendation

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
